name: Build APK Dev

on:
  push: 
    branches: 
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use cache
      id: cache-rust
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
        path: |
          /home/runner/.cargo
          /home/runner/work/tvmate/tvmate/target
          /home/runner/work/tvmate/tvmate/target
          /home/runner/work/tvmate/tvmate/tauri/src-tauri/gen/android/app/build

        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-
                
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y clang cmake libevent-dev libclang-dev libcurl4-openssl-dev curl gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r27c
        add-to-path: false
        link-to-sdk: true
    - run: rustup toolchain install nightly-2024-08-15
    - name: Add wasm32
      run: rustup target add wasm32-unknown-unknown
  
    - name: Add aarch64
      run: rustup target add aarch64-unknown-linux-gnu aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android

    - name: Install trunk
      run: cargo install trunk
    
    - name: Install tauri
      run: cargo install tauri-cli --version "^2.0.0" --locked

    - name: Configure Keystore
      run: |
        echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > tauri/src-tauri/gen/android/keystore.properties
        echo "storeFile=upload-keystore.jks" > tauri/src-tauri/gen/android/keystore.properties
        echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> tauri/src-tauri/gen/android/keystore.properties
        echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> tauri/src-tauri/gen/android/keystore.properties
        echo "password=$KEYSTORE_KEY_PASSWORD" >> tauri/src-tauri/gen/android/keystore.properties
        echo "storeFile=../keystore.jks" >> tauri/src-tauri/gen/android/keystore.properties
      env:
        PLAY_STORE_UPLOAD_KEY: ${{ secrets.RELEASE_KEYSTORE }}
        KEYSTORE_KEY_ALIAS: ${{ secrets.KEY_STORE_ALIAS }}
        KEYSTORE_KEY_PASSWORD: ${{ secrets.KEY_STORE_ALIAS_PASSWORD }}
        KEYSTORE_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
    - name: Build APK
      run: cd tauri && cargo tauri android build --apk
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}