name: Build APK Dev

on:
  push: 
    branches: 
      - "main"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  
jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use cache
      id: cache-rust
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
        path: |
          /home/runner/.cargo
          /home/runner/work/tvmate/tvmate/target
          /home/runner/work/tvmate/tvmate/target
          /home/runner/work/tvmate/tvmate/tauri/src-tauri/gen/android/app/build

        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-
                
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y clang cmake libevent-dev libclang-dev libcurl4-openssl-dev curl gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
    
    - name: Configure Keystore
      run: |
        echo "$KEYSTORE" | base64 --decode > tauri/src-tauri/gen/android/keystore.jks
        echo "storeFile=upload-keystore.jks" > tauri/src-tauri/gen/android/keystore.properties
        echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> tauri/src-tauri/gen/android/keystore.properties
        echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> tauri/src-tauri/gen/android/keystore.properties
        echo "password=$KEYSTORE_KEY_PASSWORD" >> tauri/src-tauri/gen/android/keystore.properties
        echo "storeFile=../keystore.jks" >> tauri/src-tauri/gen/android/keystore.properties
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}
        KEYSTORE_KEY_ALIAS: ${{ secrets.KEY_STORE_ALIAS }}
        KEYSTORE_KEY_PASSWORD: ${{ secrets.KEY_STORE_ALIAS_PASSWORD }}
        KEYSTORE_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r27c
        add-to-path: false
        link-to-sdk: true

    - run: rustup toolchain install nightly-2024-08-15
    - name: Add wasm32
      run: rustup target add wasm32-unknown-unknown
  
    - name: Add aarch64
      run: rustup target add aarch64-unknown-linux-gnu aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android

    - name: Install trunk
      run: cargo install trunk
    
    - name: Install tauri
      run: cargo install tauri-cli --version "^2.0.0" --locked

    - name: Build APK
      run: cd tauri && cargo tauri android build --apk
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      # First delete existing release if it exists
    - name: Delete existing release
      uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        tag_name: latest-dev
        delete_release: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    # Create new release
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest-dev
        name: Latest Development Build
        body: |
          This is an automated pre-release containing the latest build from the master branch.
          Last updated: ${{ github.event.head_commit.timestamp }}
          Commit: ${{ github.sha }}
        prerelease: true
        files: tauri/src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk
        token: ${{ secrets.GITHUB_TOKEN }}