name: Build and Deploy to Self Cloud

on:
  workflow_dispatch:  # Trigger manually


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use cache
      id: cache-rust
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        path: |
          /home/runner/.cargo
          /home/runner/work/tvmate/tvmate/target
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
            
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y clang cmake libevent-dev libclang-dev libcurl4-openssl-dev curl gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
    - run: rustup toolchain install nightly-2024-08-15
    - name: Add wasm32
      run: rustup target add wasm32-unknown-unknown

    - name: Install Cargo Leptos
      run: cargo install cargo-leptos

    - name: Build
      run: cargo leptos build --release --lib-features disable-logs
        
    - name: Build Docker image
      run: |
        docker build -t tvmate:latest .
    - name: Save Docker image to a .tar file
      run: |
        docker save tvmate:latest -o tvmate.tar
    - name: Push To SelfCloud
      run: |
        curl --location --fail --show-error 'https://cloud.deepwith.in/cloud/image/push' --form 'project_id="7f95e8c0-a9dd-441f-b2fc-f7468de8761a"' --form "token=$SELFCLOUD_TOKEN" --form 'image=@"tvmate.tar"'
      env:
        SELFCLOUD_TOKEN: ${{ secrets.SELFCLOUD_TOKEN }}